### ISSUE TITLE
The project does not run.

### ISSUE THREAD

**Issue by tejasmanohar** [fwilson42/pennapps-12-project-or-something#1]
^ Title.

**Comment by fwilson42** [comment]
no

**Comment by fwilson42** [comment]
Please submit a pull request if you think this is an issue.

**Comment by qw3rtman** [comment]
:+1: This is a huge hinderance for the community.

**Comment by tejasmanohar** [comment]
All my tests just failed because of your latest release

**Comment by fwilson42** [comment]
If tests are failing, then that's a whole other issue.

**Comment by fwilson42** [comment]
wait a second... there are no releases

**Comment by Cydrobolt** [comment]
go away

**Comment by fwilson42** [comment]
that's pretty dank
